## Let's import the dependencies

In [35]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

In [36]:
df = pd.read_csv('creditcard.csv')
df
#extracted top 5 and last 5 rows of the dataset

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 284807 entries, 0 to 284806
Data columns (total 31 columns):
 #   Column  Non-Null Count   Dtype
---  ------  --------------   -----
 0   Time    284807 non-null  float64
 1   V1      284807 non-null  float64
 2   V2      284807 non-null  float64
 3   V3      284807 non-null  float64
 4   V4      284807 non-null  float64
 5   V5      284807 non-null  float64
 6   V6      284807 non-null  float64
 7   V7      284807 non-null  float64
 8   V8      284807 non-null  float64
 9   V9      284807 non-null  float64
 10  V10     284807 non-null  float64
 11  V11     284807 non-null  float64
 12  V12     284807 non-null  float64
 13  V13     284807 non-null  float64
 14  V14     284807 non-null  float64
 15  V15     284807 non-null  float64
 16  V16     284807 non-null  float64
 17  V17     284807 non-null  float64
 18  V18     284807 non-null  float64
 19  V19     284807 non-null  float64
 20  V20     284807 non-null  float64
 21  V21     284807 non-null  float64
 22  V22     284807 non-null  float64
 23  V23     284807 non-null  float64
 24  V24     284807 non-null  float64
 25  V25     284807 non-null  float64
 26  V26     284807 non-null  float64
 27  V27     284807 non-null  float64
 28  V28     284807 non-null  float64
 29  Amount  284807 non-null  float64
 30  Class   284807 non-null  int64
dtypes: float64(30), int64(1)
memory usage: 67.4 MB

In [38]:
df.isnull().sum()
# we have no missing values in the dataset

Time      0
V1        0
V2        0
V3        0
V4        0
V5        0
V6        0
V7        0
V8        0
V9        0
V10       0
V11       0
V12       0
V13       0
V14       0
V15       0
V16       0
V17       0
V18       0
V19       0
V20       0
V21       0
V22       0
V23       0
V24       0
V25       0
V26       0
V27       0
V28       0
Amount    0
Class     0
dtype: int64

In [39]:
# distribution of legit transaction and fraud transaction
df['Class'].value_counts()

Class
0    284315
1       492
Name: count, dtype: int64

unbalanced data 
0 -> Normal transaction
1-> Fraud

In [40]:
# separating the data for analysis
legit = df[df.Class == 0]
fraud = df[df.Class == 1]

In [41]:
print(legit.shape)
print(fraud.shape)

(284315, 31)
(492, 31)

In [42]:
# statistical measure of the data
legit.Amount.describe()

count    284315.000000
mean         88.291022
std         250.105092
min           0.000000
25%           5.650000
50%          22.000000
75%          77.050000
max       25691.160000
Name: Amount, dtype: float64

In [43]:
fraud.Amount.describe()

count     492.000000
mean      122.211321
std       256.683288
min         0.000000
25%         1.000000
50%         9.250000
75%       105.890000
max      2125.870000
Name: Amount, dtype: float64

In [44]:
df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,94838.202258,0.008258,-0.006271,0.012171,-0.007860,0.005453,0.002419,0.009637,-0.000987,0.004467,...,-0.000644,-0.001235,-0.000024,0.000070,0.000182,-0.000072,-0.000089,-0.000295,-0.000131,88.291022
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

Building a sample dataset having similar distribution of normal transactions and fraud transactions

In [45]:
legit_sample = legit.sample(n=492)
# this randomly selects 492 samples from the legit dataset

concatenating two dataframes

In [46]:
new_df = pd.concat([legit_sample, fraud], axis=0)
new_df.head()
new_df.tail()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
279863,169142.0,-1.927883,1.125653,-4.518331,1.749293,-1.566487,-2.010494,-0.882850,0.697211,-2.064945,...,0.778584,-0.319189,0.639419,-0.294885,0.537503,0.788395,0.292680,0.147968,390.00,1
280143,169347.0,1.378559,1.289381,-5.004247,1.411850,0.442581,-1.326536,-1.413170,0.248525,-1.127396,...,0.370612,0.028234,-0.145640,-0.081049,0.521875,0.739467,0.389152,0.186637,0.76,1
280149,169351.0,-0.676143,1.126366,-2.213700,0.468308,-1.120541,-0.003346,-2.234739,1.210158,-0.652250,...,0.751826,0.834108,0.190944,0.032070,-0.739695,0.471111,0.385107,0.194361,77.89,1
281144,169966.0,-3.113832,0.585864,-5.399730,1.817092,-0.840618,-2.943548,-2.208002,1.058733,-1.632333,...,0.583276,-0.269209,-0.456108,-0.183659,-0.328168,0.606116,0.884876,-0.253700,245.00,1
281674,170348.0,1.991976,0.158476,-2.583441,0.408670,1.151147,-0.096695,0.223050,-0.068384,0.577829,...,-0.164350,-0.295135,-0.072173,-0.450261,0.313267,-0.289617,0.002988,-0.015309,42.53,1

In [47]:
new_df['Class'].value_counts()

Class
0    492
1    492
Name: count, dtype: int64

In [48]:
new_df.groupby('Class').mean()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
Class,,,,,,,,,,,,,,,,,,,,,
0,93877.621951,-0.079578,0.035619,0.125448,-0.023194,0.018481,-0.025888,0.121005,0.012254,-0.012408,...,0.027930,0.000546,0.049284,-0.001606,0.000363,-0.035985,-0.003784,0.018584,0.000744,91.976606
1,80746.806911,-4.771948,3.623778,-7.033281,4.542029,-3.151225,-1.397737,-5.568731,0.570636,-2.581123,...,0.372319,0.713588,0.014049,-0.040308,-0.105130,0.041449,0.051648,0.170575,0.075667,122.211321

In [49]:
X =     new_df.drop(columns='Class', axis=1)
Y =    new_df['Class']

In [50]:
print(X)

            Time        V1        V2        V3        V4        V5        V6  \
217981  141121.0  1.332500 -2.334960 -1.845919 -0.535627 -0.611234  0.367739
73022    54942.0 -0.653193  0.800859  1.151981  0.158688 -0.785617  0.245530
14276    25344.0 -0.995183 -0.039833  1.587280 -1.889184  0.086393  0.110665
6599      8052.0 -0.650541  0.188489  2.108170  0.863351 -1.075652  0.393014
122819   76700.0 -1.537003  2.028363  0.261397 -0.014619  0.825862  0.045663
...          ...       ...       ...       ...       ...       ...       ...
279863  169142.0 -1.927883  1.125653 -4.518331  1.749293 -1.566487 -2.010494
280143  169347.0  1.378559  1.289381 -5.004247  1.411850  0.442581 -1.326536
280149  169351.0 -0.676143  1.126366 -2.213700  0.468308 -1.120541 -0.003346
281144  169966.0 -3.113832  0.585864 -5.399730  1.817092 -0.840618 -2.943548
281674  170348.0  1.991976  0.158476 -2.583441  0.408670  1.151147 -0.096695

              V7        V8        V9  ...       V20       V21       V22  \
217981 -0.106805 -0.167695 -0.285750  ...  0.945455  0.756769  1.516982
73022   0.106094  0.574465 -0.365024  ... -0.197109  0.207080  0.586927
14276   0.371166 -0.181099 -1.065219  ... -0.103440  0.053965  0.337669
6599    0.213789 -0.021269  0.154101  ... -0.484201 -0.704450 -1.157936
122819 -0.836231 -2.123427 -1.699727  ...  0.579738 -1.223682  0.320244
...          ...       ...       ...  ...       ...       ...       ...
279863 -0.882850  0.697211 -2.064945  ...  1.252967  0.778584 -0.319189
280143 -1.413170  0.248525 -1.127396  ...  0.226138  0.370612  0.028234
280149 -2.234739  1.210158 -0.652250  ...  0.247968  0.751826  0.834108
281144 -2.208002  1.058733 -1.632333  ...  0.306271  0.583276 -0.269209
281674  0.223050 -0.068384  0.577829  ... -0.017652 -0.164350 -0.295135

             V23       V24       V25       V26       V27       V28  Amount
217981 -0.583772  0.392047  0.389262  0.222511 -0.094925 -0.000601  450.00
73022   0.109057  0.272158 -0.478157  0.253089 -0.167003 -0.055236   77.50
14276  -0.090478 -0.286068  0.045066 -0.476159 -0.405522 -0.155737   32.92
6599    0.225112  0.269809 -0.550182 -0.575947  0.111742  0.117420  136.74
122819 -0.653011 -0.362265  0.287211  0.404107 -0.112512  0.061352    0.76
...          ...       ...       ...       ...       ...       ...     ...
279863  0.639419 -0.294885  0.537503  0.788395  0.292680  0.147968  390.00
280143 -0.145640 -0.081049  0.521875  0.739467  0.389152  0.186637    0.76
280149  0.190944  0.032070 -0.739695  0.471111  0.385107  0.194361   77.89
281144 -0.456108 -0.183659 -0.328168  0.606116  0.884876 -0.253700  245.00
281674 -0.072173 -0.450261  0.313267 -0.289617  0.002988 -0.015309   42.53

[984 rows x 30 columns]

In [51]:
print(Y)

217981    0
73022     0
14276     0
6599      0
122819    0
         ..
279863    1
280143    1
280149    1
281144    1
281674    1
Name: Class, Length: 984, dtype: int64

Splitting the data into training and testing

In [52]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size=0.2, stratify=Y, random_state=2)

In [53]:
print(X.shape, X_train.shape, X_test.shape)

(984, 30) (787, 30) (197, 30)

Model training

In [54]:
model = LogisticRegression()

Training model with training data

In [55]:
model.fit(X_train, Y_train)

LogisticRegression()

Evaluating our model based on accuracy score

In [56]:
X_train_prediction = model.predict(X_train)
training_data_accuracy = accuracy_score(X_train_prediction, Y_train)
X_train

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V20,V21,V22,V23,V24,V25,V26,V27,V28,Amount
100623,67571.0,-0.758469,-0.045410,-0.168438,-1.313275,-1.901763,0.739433,3.071892,-0.483422,0.618203,...,-0.032500,0.042619,0.397224,0.072229,-0.242276,0.560916,-0.540955,0.150606,-0.117140,549.06
30437,35922.0,1.008698,0.260927,-0.404836,2.343436,0.636451,0.135540,0.603438,-0.098125,-0.947972,...,0.049526,0.026413,-0.203316,-0.281175,-0.773714,0.708917,0.138954,-0.050296,0.018432,125.25
83808,60038.0,-0.465668,0.443606,1.396405,1.074284,0.162992,-0.167784,0.540689,0.035233,-0.056728,...,0.155387,-0.106907,-0.303097,0.096416,-0.148412,-0.372651,-0.508044,0.171783,0.177637,63.79
22653,32361.0,1.162349,0.662246,0.085488,2.511350,0.193049,-0.826499,0.631718,-0.308157,-1.099469,...,-0.077747,0.008938,-0.059415,-0.139203,0.387904,0.726707,0.064449,-0.044508,0.016633,37.92
200560,133481.0,1.721867,0.667619,-0.634118,4.314196,0.026300,-0.103233,-0.525856,0.210457,-0.226011,...,-0.129211,-0.118479,-0.393832,0.269933,-0.359724,-0.583916,-0.191888,0.058059,0.054803,53.06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14702,25928.0,1.152186,-1.157830,-0.733491,-0.942890,-0.467324,-0.262326,-0.027704,-0.275067,-0.687204,...,-0.039222,-0.439349,-1.083685,-0.329970,-0.923146,0.471623,1.538217,-0.135084,0.011464,198.00
196050,131340.0,-0.211898,0.504185,1.421012,0.820627,0.549775,0.325151,0.285048,-0.488967,0.397512,...,0.381589,-0.113887,0.074734,-0.017104,0.487069,-0.982463,-0.333402,-0.507495,-0.100210,1.18
223618,143456.0,-2.006582,3.676577,-5.463811,7.232058,-1.627859,-0.996755,-4.299833,2.268867,-3.651067,...,0.474414,0.713907,-0.063868,0.167947,-0.449864,0.023702,0.536905,0.485864,-0.042393,1.00
43061,41353.0,-15.020981,8.075240,-16.298091,5.664820,-11.918153,-4.246957,-14.716668,9.435084,-6.795398,...,-0.995787,2.525115,-0.832074,-0.186117,0.429781,0.697103,0.056031,-1.310888,-0.707403,34.12
143322,85277.0,0.974672,-1.008962,-0.692559,-1.970639,-0.671598,-1.148701,0.316684,-0.228896,1.694662,...,0.212240,0.120557,0.157090,-0.425659,0.036021,0.927541,-0.671918,0.001255,0.026438,189.38

In [57]:
print('Accuracy score (training data) : ', training_data_accuracy)

Accuracy score (training data) :  0.9440914866581956

If accuracy score is more than 75% (or 0.75 )then the model is good

Training on test data

In [58]:
X_test_prediction = model.predict(X_test)
test_data_accuracy = accuracy_score(X_test_prediction, Y_test)

In [59]:
print('Accuracy score (test data) : ', test_data_accuracy)

Accuracy score (test data) :  0.934010152284264

In [60]:
from sklearn.metrics import f1_score

# Calculate F1 score for test set
f1_test = f1_score(Y_test, X_test_prediction)
print("F1 score for test set:", f1_test)

# Calculate F1 score for train set
f1_train = f1_score(Y_train, X_train_prediction)
print("F1 score for train set:", f1_train)

F1 score for test set: 0.9297297297297297
F1 score for train set: 0.9427083333333333

In [75]:

# Create a sample data for prediction
sample_data = pd.DataFrame({
    'Time': [123456],
    'V1': [-2.035324],
    'V2': [-1.219774],
    'V3': [0.996884],
    'V4': [-1.212205],
    'V5': [1.534749],
    'V6': [-0.589758],
    'V7': [0.910826],
    'V8': [-0.159925],
    'V9': [0.331695],
    'V10': [-0.952608],
    'V11': [0.746460],
    'V12': [0.902233],
    'V13': [0.041310],
    'V14': [-0.114631],
    'V15': [-1.054759],
    'V16': [0.295377],
    'V17': [-1.282610],
    'V18': [0.3736042],
    'V19': [-1.012938],
    'V20': [-0.008903],
    'V21': [0.136846],
    'V22': [0.431533],
    'V23': [0.243435],
    'V24': [0.688040],
    'V25': [0.448586],
    'V26': [-0.906477],
    'V27': [-0.203240],
    'V28': [0.081577],
    'Amount': [4120.0],
})

predictions = model.predict(sample_data)

# Interpret the predictions
if predictions[0] == 0:
    print("The transaction is predicted to be non-fraudulent.")
else:
    print("The transaction is predicted to be fraudulent.")

The transaction is predicted to be fraudulent.